name: 'fetch-py-project-version'
description: 'Fetch version of a particular python project'

outputs:
  version:
    description: 'Version of the python project'
    value: ${{ steps.fetch-version.outputs.version }}

runs:
  using: composite
  steps:
    - name: Fetch version
      id: fetch-version
      shell: bash
      run: |
        version=$(awk -F '"' '/^version *= */ {print $2}' pyproject.toml)
        echo "version=${version}"

        echo "version=${version}" >> $GITHUB_OUTPUT
