name: docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  detect-changed-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          # must be enabled for the below steps to work
          persist-credentials: true
      - name: Get changed files in the docs folder
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.5
        with:
          files_ignore: README.md

      - name: List changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          echo "List all the files that have changed: ${ALL_CHANGED_FILES}"

  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v5
  #       with:
  #         persist-credentials: false
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ vars.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     - name: Build and push
  #       uses: docker/build-push-action@v6
  #       with:
  #         platforms: linux/amd64,linux/arm64
  #         push: true
  #         tags: user/app:latest
  #         cache-from: type=gha
  #         cache-to: type=gha,mode=max
