name: release

on:
  push:
    tags:
      - v*

jobs:
  detect-changed-dirs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Get changed dirs
        id: changed-dirs
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.5
        with:
          dir_names: true
          dir_names_max_depth: '1'
          files_ignore: |
            README.md
            .github/**
          json: true
          matrix: true

      - name: List changed dirs
        env:
          ALL_CHANGED_DIRS: ${{ steps.changed-dirs.outputs.all_changed_files }}
        run: |
          echo "Changed Dirs: ${ALL_CHANGED_DIRS}"
    outputs:
      all_changed_dirs: ${{ steps.changed-dirs.outputs.all_changed_dirs }}
