name: release

on:
  push:
    tags:
      - v*

jobs:
  detect-changed-dirs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Get changed dirs
        id: changed-dirs
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.5
        with:
          dir_names: true
          dir_names_max_depth: '1'
          files_ignore: |
            README.md
            .github/**
          json: true
          matrix: true

      - name: List changed dirs
        env:
          ALL_CHANGED_DIRS: ${{ steps.changed-dirs.outputs.all_changed_files }}
        run: |
          echo "Changed Dirs: ${ALL_CHANGED_DIRS}"
    outputs:
      all_changed_dirs: ${{ steps.changed-dirs.outputs.all_changed_dirs }}

  container-image:
    runs-on: ubuntu-latest
    needs: [detect-changed-dirs]
    strategy:
      matrix:
        dirs: ${{ fromJson(needs.detect-changed-dirs.outputs.all_changed_dirs) }}
    defaults:
      run:
        working-directory: ${{ matrix.dirs }}
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            vimalpaliwal/tinyurl-mcp-server
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=latest
            type=sha
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.dirs }}
          file: ${{ matrix.dirs }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
  pypi-publish:
    runs-on: ubuntu-latest
    needs: [detect-changed-dirs]
    environment:
      name: pypi
      url: https://pypi.org/p/<your-pypi-project-name>
    permissions:
      id-token: write
    strategy:
      matrix:
        dirs: ${{ fromJson(needs.detect-changed-dirs.outputs.all_changed_dirs) }}
    defaults:
      run:
        working-directory: ${{ matrix.dirs }}
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Build package distributions
        run: uv build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
