name: release

on:
  push:
    tags:
      - v*
  pull_request:

env:
  DOCKERHUB_REGISTRY: vimalpaliwal

jobs:
  detect-changed-dirs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 0
          fetch-tags: true

      # Handle the “first tag” case
      - name: Get previous tag
        id: prev-tag
        run: |
          git fetch --tags --depth=1
          echo "tag=$(git tag --sort=-creatordate | sed -n 2p)" >> $GITHUB_OUTPUT

      - name: Get all mcp dirs
        if: steps.prev-tag.outputs.tag == ''
        id: all-dirs
        run: |
          ALL_DIRS=("$(ls -d */ | tr -d '/')")
          ALL_DIRS_JSON="$(printf '%s\n' "${ALL_DIRS[@]}" | jq -R . | jq -sc .)"

          echo "all_changed_dirs=${ALL_DIRS_JSON}" >> $GITHUB_OUTPUT

      - name: Get changed dirs
        id: changed-dirs
        if: steps.prev-tag.outputs.tag != ''
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.5
        with:
          dir_names: true
          dir_names_max_depth: '1'
          files_ignore: |
            README.md
            .github/**
          json: true
          matrix: true

      - name: List changed dirs
        id: list-changed-dirs
        env:
          ALL_CHANGED_DIRS: ${{ steps.prev-tag.outputs.tag == '' && steps.all-dirs.outputs.all_changed_dirs || steps.changed-dirs.outputs.all_changed_files }}
        run: |
          echo "Changed Dirs: ${ALL_CHANGED_DIRS}"

          echo "all_changed_dirs=${ALL_CHANGED_DIRS}" >> $GITHUB_OUTPUT
    outputs:
      all_changed_dirs: ${{ steps.list-changed-dirs.outputs.all_changed_dirs }}

  image-publish:
    runs-on: ubuntu-latest
    needs: [detect-changed-dirs]
    if: needs.detect-changed-dirs.outputs.all_changed_dirs != '[]'
    strategy:
      matrix:
        dirs: ${{ fromJson(needs.detect-changed-dirs.outputs.all_changed_dirs) }}
    defaults:
      run:
        working-directory: ${{ matrix.dirs }}
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.DOCKERHUB_REGISTRY }}/${{ matrix.dirs }}-mcp
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,value=tag
            type=sha,prefix=
      - name: Build and publish image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.dirs }}
          file: ${{ matrix.dirs }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}
          repository: ${{ env.DOCKERHUB_REGISTRY }}/${{ matrix.dirs }}-mcp
          readme-filepath: ${{ matrix.dirs }}/README.md

  pypi-publish:
    runs-on: ubuntu-latest
    needs: [detect-changed-dirs]
    if: needs.detect-changed-dirs.outputs.all_changed_dirs != '[]'
    environment:
      name: release
      url: https://pypi.org/p/${{ matrix.dirs }}-mcp
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        dirs: ${{ fromJson(needs.detect-changed-dirs.outputs.all_changed_dirs) }}
    defaults:
      run:
        working-directory: ${{ matrix.dirs }}
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Build package distributions
        run: uv build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ${{ matrix.dirs }}/dist
